### ISSUE TITLE
More Encryption or Seeds

### ISSUE THREAD

**Issue by BunBun22** [SethClydesdale/cunny-code#1]
I would like more encryption if possible, for example so that only my friends can decrypt my messages. The tool itself is really great and fun to use, but it is quite easy to find and people can easily decrypt my messages once they find this github.

**Comment by SethClydesdale** [comment]
Hello @BunBun22!

I think that's actually a good idea, especially for circles of friends. I'll consider looking into researching some methods for encrypting the output, perhaps with a password.

**Comment by SethClydesdale** [comment]
Hello again, @BunBun22!

As of today, you can now set a password to encrypt your messages. Just tick the "Set Password" checkbox on the homepage, input a password, and you're set! You can find additional information on Arona's encryption/decryption methods [here](https://sethclydesdale.github.io/cunny-code/arona/#encryption-and-decryption).

**Comment by BunBun22** [comment]
Thanks for adding my request. I'm glad it proved useful, and that it accidentally added support for other languages is a pretty funny side effect. lol
